# Generated by Django 6.1 on 2026-08-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_subscriber_is_paid_alter_subscriber_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='last_renewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='amount',
            field=models.IntegerField(default=40000),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='package',
            field=models.CharField(default='Economy', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='phone',
            field=models.CharField(default='0000', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
