# Generated by Django 6.1 on 2026-08-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_subscriber_last_renewed_at_alter_subscriber_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='package',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
